name: CI/CD Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible sshpass

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        echo "$PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ansible-playbook ansible/deploy.yml -i ansible/hosts --private-key key.pem
      shell: bash
