name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"  # 👈 Add this line

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Run Ansible playbook
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook -i ansible/hosts ansible/deploy.yml --private-key key.pem

